# Copyright (c) HashiCorp, Inc.

name: 'Setup the HashiCorp Cloud Platform CLI'
author: 'HashiCorp, Inc.'
description: |-
  Downloads and installs the HashiCorp Cloud Platform CLI, making it available
  on the PATH for future steps.

branding:
  icon: 'terminal'
  color: 'gray-dark'

inputs:
  version:
    required: false
    description: |-
      A string specifying which version of the `hcp` CLI to use. The following are
      valid version strings:

        - ``: Use the currently installed version of the `hcp` CLI. If the `hcp`
        CLI is not installed, the latest version will be installed.
        - `latest`: Use the latest version of the `hcp` CLI.
        - Specific version (e.g. `0.3.0`): Specifies the exact version of the
        `hcp` CLI to use.
        - Version constraint (e.g. `>= 0.3.0`): Specifies a version constraint
        for the `hcp` CLI. The latest version that satisfies the constraint will
        be used. See https://www.npmjs.com/package/semver for details on constructing
        a version constraint string.

  project_id:
    description: |-
      Configure the default HCP Project ID for the `hcp` CLI. This is equivalent to
      running `hcp profile set project_id <project_id>`. Individual commands can
      override this value by setting the `--project` flag.
    required: false

runs:
  using: node20
  main: dist/index.js
